### ISSUE TITLE
App not showing leader list?

### ISSUE THREAD

**Issue by Orangefellow** [datvm/Civ6MutationMode#5]
Hi there. I sbsolutely adore your mod and wanted to try out some specific combo's However, upon opening up the app, I only seem to see the list of Civ's and their abilities, with the "leader" box being completely blank. I'e tried re-installing the app, but this problem persists. This mod is a fantastic idea and has reinvigorated the game for me, I love it and would love to explore it further If anyone can help me out, I'd really appreciate it!

**Comment by datvm** [comment]
Did this work for you?

> Sometimes the game dump an uncompleted DebugGameplay.sql, and you may see the list of Civ/Leaders in the app incomplete. Don't worry, just close the app, enter the game, start a new map so the game can create another DebugGameplay.sql, and start the app again.

**Comment by Orangefellow** [comment]
No, sadlyy that didn't work; the leader list is still empty I've tried extracting the program to different folders in different routes, but always get this issue.

**Comment by datvm** [comment]
Can you try attaching the `DebugGameplay.sql` file please? It should be in your Documents folder (use the Search in File Explorer feature)

**Comment by Orangefellow** [comment]
Hi there. I think the problem is something to do with the order in which I install the app, launch a test game and then go check the app. I got leaders to show up last time after some foolingg around, but haen't actually played a game since then. I'll keep you posted on the issue and whether I can figure out exactly what's up. Thanks so much for responding so quickly though!

**Comment by Orangefellow** [comment]
> Can you try attaching the `DebugGameplay.sql` file please? It should be in your Documents folder (use the Search in File Explorer feature)

Okay, it APPEARS this issue occurs when the mod "Sui Generis" is enabled when creating a game. "Sui Generis" is a very popular mod that adds some regional abilities. It appears there isn't a way to get the two mods to play nicely with one another, and when Sui Generis is enabled even after creating a game with this mod/app, the Sui Generis abilities don't show up. This is somewhat unusual, as when ust using the regular mod, Sui Generis abilities and Mutation mode can both be active. Do you think there's any wayy around this? I understand it's pretty niche.

**Comment by datvm** [comment]
Hi unfortunately I am not active in the game or modding anymore and this project was 2 years ago so I doubt there will be any fix for this.
